"""Convert tabular enrollment records to EDI 834 wire format.

Produces compliant 834 (Benefit Enrollment and Maintenance) files from
the tabular enrollment DataFrame generated by synthetic_enrollment.py.

Segment mapping
---------------
ISA  → Interchange control header
GS   → Functional group header
ST   → Transaction set header (834)
BGN  → Beginning segment
INS  → Insured benefit (member relationship, maintenance type)
REF  → Reference identification (SSN, member ID)
NM1  → Individual name
DMG  → Demographic information (DOB, gender, marital status)
DTP  → Date/time period (coverage dates)
HD   → Health coverage
SE   → Transaction set trailer
GE   → Functional group trailer
IEA  → Interchange control trailer

All reference data (group, plan, benefit keys) comes from the member denorm
via the enrollment DataFrame. Only synthetic PII fields are generated.
"""

from datetime import datetime
import pandas as pd

# EDI delimiters
ELEMENT_SEP = "*"
SEGMENT_TERM = "~"
SUB_ELEMENT_SEP = ":"


def _pad(val, length):
    """Left-pad or truncate a string to exact length."""
    s = str(val or "")
    return s[:length].ljust(length)


def _clean(val):
    """Clean a value for EDI output — no delimiters, no newlines."""
    s = str(val or "").strip()
    return s.replace("*", "").replace("~", "").replace("\n", "")


def _date_compact(val):
    """Convert date string to CCYYMMDD format."""
    if not val or str(val).startswith("9999"):
        return "99991231"
    try:
        dt = pd.to_datetime(val)
        return dt.strftime("%Y%m%d")
    except Exception:
        return str(val).replace("-", "")[:8]


def _build_isa(sender_id, receiver_id, control_number, date_str):
    """Build ISA interchange control header."""
    dt = pd.to_datetime(date_str)
    elements = [
        "ISA",
        "00",               # Authorization qualifier
        _pad("", 10),       # Authorization info
        "00",               # Security qualifier
        _pad("", 10),       # Security info
        "ZZ",               # Sender qualifier
        _pad(sender_id, 15),
        "ZZ",               # Receiver qualifier
        _pad(receiver_id, 15),
        dt.strftime("%y%m%d"),  # Date
        dt.strftime("%H%M"),    # Time
        "^",                # Repetition separator
        "00501",            # Version
        _pad(control_number, 9),
        "0",                # Ack requested
        "T",                # Usage indicator (T=test)
        SUB_ELEMENT_SEP,    # Sub-element separator
    ]
    return ELEMENT_SEP.join(elements) + SEGMENT_TERM


def _build_gs(sender_id, receiver_id, control_number, date_str):
    """Build GS functional group header."""
    dt = pd.to_datetime(date_str)
    elements = [
        "GS",
        "BE",               # Functional identifier (Benefit Enrollment)
        _clean(sender_id),
        _clean(receiver_id),
        dt.strftime("%Y%m%d"),
        dt.strftime("%H%M"),
        str(control_number),
        "X",                # Responsible agency
        "005010X220A1",     # Version
    ]
    return ELEMENT_SEP.join(elements) + SEGMENT_TERM


def _build_st(control_number):
    """Build ST transaction set header."""
    elements = [
        "ST",
        "834",              # Transaction set ID
        _pad(control_number, 4),
        "005010X220A1",     # Implementation convention
    ]
    return ELEMENT_SEP.join(elements) + SEGMENT_TERM


def _build_bgn(ref_id, date_str, transaction_type="00"):
    """Build BGN beginning segment."""
    dt = pd.to_datetime(date_str)
    elements = [
        "BGN",
        transaction_type,
        _clean(ref_id),
        dt.strftime("%Y%m%d"),
        dt.strftime("%H%M"),
        "",                 # Time zone (optional)
        "",                 # Reference ID (optional)
        "",                 # Transaction type (optional)
        "4",                # Action code (4=verify, 2=change)
    ]
    return ELEMENT_SEP.join(elements) + SEGMENT_TERM


def _build_member_segments(row):
    """Build all segments for a single member/subscriber."""
    segments = []

    # INS - Insured benefit
    rel = _clean(row.get("MEME_REL", ""))
    # Map FACETS MEME_REL to EDI relationship codes
    rel_map = {"M": "18", "S": "01", "D": "19"}  # 18=self, 01=spouse, 19=child
    ins_rel = rel_map.get(rel, "18")
    is_subscriber = "Y" if rel in ("M", "") else "N"
    maint_type = _clean(row.get("MAINTENANCE_TYPE", "021"))
    maint_reason = _clean(row.get("MAINTENANCE_REASON", "AI"))
    benefit_status = _clean(row.get("BENEFIT_STATUS", "A"))
    # Map benefit status
    ben_map = {"A": "A", "T": "S"}  # A=active, S=termed
    ins_ben = ben_map.get(benefit_status, "A")

    segments.append(ELEMENT_SEP.join([
        "INS", is_subscriber, ins_rel, maint_type, maint_reason,
        ins_ben, "", "", "", "", "", "", "", "",
    ]) + SEGMENT_TERM)

    # REF - SSN
    ssn = _clean(row.get("MEME_SSN", ""))
    if ssn:
        segments.append(ELEMENT_SEP.join([
            "REF", "0F", ssn,
        ]) + SEGMENT_TERM)

    # REF - Subscriber ID
    sbsb_id = _clean(row.get("SBSB_ID", ""))
    if sbsb_id:
        segments.append(ELEMENT_SEP.join([
            "REF", "1L", sbsb_id,
        ]) + SEGMENT_TERM)

    # NM1 - Member name (IL = Insured or subscriber)
    nm1_qualifier = "IL" if is_subscriber == "Y" else "IL"
    last_name = _clean(row.get("MEME_LAST_NAME", ""))
    first_name = _clean(row.get("MEME_FIRST_NAME", ""))
    mid_init = _clean(row.get("MEME_MID_INIT", ""))
    segments.append(ELEMENT_SEP.join([
        "NM1", nm1_qualifier, "1", last_name, first_name,
        mid_init, "", "", "34", ssn,
    ]) + SEGMENT_TERM)

    # DMG - Demographics
    dob = _date_compact(row.get("MEME_BIRTH_DT", ""))
    gender = _clean(row.get("MEME_SEX", ""))
    # Map gender
    gender_map = {"M": "M", "F": "F"}
    edi_gender = gender_map.get(gender, "U")
    marital = _clean(row.get("MEME_MARITAL_STATUS", ""))
    marital_map = {"M": "M", "S": "I", "D": "B", "W": "X"}
    edi_marital = marital_map.get(marital, "I")

    segments.append(ELEMENT_SEP.join([
        "DMG", "D8", dob, edi_gender, edi_marital,
    ]) + SEGMENT_TERM)

    # DTP - Coverage effective date (348 = plan begin)
    eff_dt = _date_compact(row.get("COVERAGE_EFF_DT", ""))
    if eff_dt:
        segments.append(ELEMENT_SEP.join([
            "DTP", "348", "D8", eff_dt,
        ]) + SEGMENT_TERM)

    # DTP - Coverage term date (349 = plan end), only if not 99991231
    term_dt = _date_compact(row.get("COVERAGE_TERM_DT", ""))
    if term_dt and term_dt != "99991231":
        segments.append(ELEMENT_SEP.join([
            "DTP", "349", "D8", term_dt,
        ]) + SEGMENT_TERM)

    # HD - Health coverage
    ins_line = _clean(row.get("INS_LINE_CD", "HLT"))
    cspd_cat = _clean(row.get("CSPD_CAT", ""))
    plds_desc = _clean(row.get("PLDS_DESC", ""))
    segments.append(ELEMENT_SEP.join([
        "HD", maint_type, "", ins_line, cspd_cat, plds_desc,
    ]) + SEGMENT_TERM)

    return segments


def enrollment_to_edi(
    enrollment_df: pd.DataFrame,
    sender_id: str = "CARESOURCE",
    receiver_id: str = "RECEIVER",
    control_number: int = 1,
) -> str:
    """Convert enrollment DataFrame to EDI 834 string.

    Parameters
    ----------
    enrollment_df : pd.DataFrame
        Enrollment records from generate_synthetic_enrollments().
    sender_id : str
        Interchange sender ID (ISA06).
    receiver_id : str
        Interchange receiver ID (ISA08).
    control_number : int
        Interchange control number.

    Returns
    -------
    str : Complete EDI 834 file content.
    """
    if enrollment_df.empty:
        return ""

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    # ISA
    lines.append(_build_isa(sender_id, receiver_id, control_number, now))

    # GS
    lines.append(_build_gs(sender_id, receiver_id, control_number, now))

    # ST
    st_control = str(control_number).zfill(4)
    lines.append(_build_st(st_control))

    # BGN
    txn_id = enrollment_df.iloc[0].get("TRANSACTION_ID", f"TXN{control_number}")
    txn_dt = enrollment_df.iloc[0].get("TRANSACTION_DT", now[:10])
    lines.append(_build_bgn(txn_id, txn_dt))

    # Sponsor/payer name (1000A loop)
    grgr_name = _clean(enrollment_df.iloc[0].get("GRGR_NAME", sender_id))
    grgr_id = _clean(enrollment_df.iloc[0].get("GRGR_ID", ""))
    lines.append(ELEMENT_SEP.join([
        "N1", "P5", grgr_name, "FI", grgr_id,
    ]) + SEGMENT_TERM)

    # Member segments (2000 loop)
    segment_count = 4  # ST + BGN + N1 + (SE counted at end)
    for _, row in enrollment_df.iterrows():
        member_segs = _build_member_segments(row)
        lines.extend(member_segs)
        segment_count += len(member_segs)

    # SE - include SE itself in count
    segment_count += 1
    lines.append(ELEMENT_SEP.join([
        "SE", str(segment_count), st_control,
    ]) + SEGMENT_TERM)

    # GE
    lines.append(ELEMENT_SEP.join([
        "GE", "1", str(control_number),
    ]) + SEGMENT_TERM)

    # IEA
    lines.append(ELEMENT_SEP.join([
        "IEA", "1", _pad(control_number, 9),
    ]) + SEGMENT_TERM)

    return "\n".join(lines)
